Map<int, String> WeatherCodeImage = {
  0: "assets/images/Sunny.svg",
  1: "assets/images/Clouds.svg",
  2: "assets/images/Clouds.svg",
  3: "assets/images/Overcast.svg",
  45: "assets/images/Haze.svg",
  48: "assets/images/Haze.svg",
  51: "assets/images/Rainy.svg",
  53: "assets/images/Rainy.svg",
  55: "assets/images/Rainy.svg",
  56: "assets/images/Rainy.svg",
  57: "assets/images/Rainy.svg",
  61: "assets/images/Rainy.svg",
  63: "assets/images/Rainy.svg",
  65: "assets/images/Rainy.svg",
  66: "assets/images/Rainy.svg",
  67: "assets/images/Rainy.svg",
  80: "assets/images/Rainy.svg",
  81: "assets/images/Rainy.svg",
  82: "assets/images/Rainy.svg",
  71: "assets/images/Snow.svg",
  73: "assets/images/Snow.svg",
  75: "assets/images/Snow.svg",
  85: "assets/images/Snow.svg",
  86: "assets/images/Snow.svg",
  95: "assets/images/Thunderstorm.svg",
  96: "assets/images/Thunderstorm.svg",
  99: "assets/images/Thunderstorm.svg",
};

Map<int, String> WeatherCodeText = {
  0: "Clear Sky",
  1: "Mainly Clear",
  2: "Some Clouds",
  3: "OverCast",
  45: "Fog",
  48: "Icy Fog",
  51: "Light Drizzle",
  53: "Moderate Drizzle",
  55: "Dense Drizzle",
  56: "Freezing Drizzle",
  57: "Freezing Drizzle",
  61: "Slight Rain",
  63: "Moderate Rain",
  65: "Heavy Rain",
  66: "Freezing Rain",
  67: "Freezing Rain",
  71: "Slight Snow Fall",
  73: "Moderate Snow Fall",
  75: "Snow Fall",
  77: "Snow Grains",
  80: "Rain Showers",
  81: "Rain Showers",
  82: "Violent Rain",
  85: "Snow Showers",
  86: "Snow Showers",
  95: "Thunder Storm",
  96: "Thunderstorm with hail",
  99: "Thunderstorm with hail",
};
